let productos = [{


        id: 1,
        imagen: './img/lamparamesa2.png',
        nombre: 'Lampara',
        categoria: 'Iluminación',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },
    {
        id: 2,
        imagen: './img/relojpared.png',
        nombre: 'Reloj de pared',
        categoria: 'Relojes',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },
    {
        id: 3,
        imagen: './img/velador.png',
        nombre: 'Velador',
        categoria: 'Muebles',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },
    {
        id: 4,
        imagen: './img/mesacentro.png',
        nombre: 'Mesa de Centro',
        categoria: 'Muebles',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },
    {
        id: 5,
        imagen: './img/sillon 2.png',
        nombre: 'Sofá 3 cuerpos',
        categoria: 'Muebles',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },
    {
        id: 6,
        imagen: './img/sillamecedora.png',
        nombre: 'Silla mecedora',
        categoria: 'Muebles',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },
    {
        id: 7,
        imagen: './img/tvvintage.png',
        nombre: 'Televisor Vintage',
        categoria: 'Televisores',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },
    {
        id: 8,
        imagen: './img/radioreloj.png',
        nombre: 'Radio reloj',
        categoria: 'Relojes',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },
    {
        id: 9,
        imagen: './img/nintendo64.png',
        nombre: 'Nintendo 64',
        categoria: 'Consolas',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },
    {
        id: 10,
        imagen: './img/supernintendo.png',
        nombre: 'Super Nintendo',
        categoria: 'Consolas',
        precio: 4999,
        descripcion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deserunt.',
    },

];